import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <Header />

      <main>
        {/* sidbar */}
        {/* feed */}
        {/* widgest */}
      </main>
    </div>
  );
}

export async function getServerSidProps(context) {
  //  get the user
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
